export { GitVaultyError, SecretFileConflictError, TrackedPlaintextError } from "./errors.js";
export { normalizeUsername, parseRecipient } from "./recipient.js";
export { findRepository, type Repository } from "./repository.js";
export {
  AGENT_SKILL_RELATIVE_FILE,
  agentSkillStatus,
  installAgentSkill,
  type AgentSkillInstallResult,
  type AgentSkillStatus,
} from "./agent-skill.js";
export {
  cleanupAbandonedEditDirectories,
  DEFAULT_EDIT_TEMP_GRACE_PERIOD_MS,
  type EditTempCleanupOptions,
  type EditTempCleanupResult,
} from "./edit-temp.js";
export {
  createIdentity,
  currentIdentity,
  currentRecipient,
  deriveIdentity,
  identityFile,
  parseSigningKey,
  readIdentity,
  readStoredIdentity,
  restoreIdentity,
  signMessage,
  verifyMessage,
  type StoredIdentity,
} from "./key.js";
export {
  normalizeGitVaultyUser,
  normalizeGitVaultyGroup,
  normalizeGroupName,
  normalizeFileGrant,
  normalizeSecretFile,
  fileGrantFor,
  filesForUser,
  readRegistry,
  writeRegistry,
  recipientsFor,
  usernamesFor,
  type Registry,
  type GitVaultyUser,
  type GitVaultyGroup,
  type SecretFileGrant,
} from "./registry.js";
export {
  appendGroupPolicy,
  createGroupPolicy,
  currentGroupPolicy,
  policyHash,
  type GroupPolicy,
  type GroupPolicyMember,
} from "./group-policy.js";
export {
  initialize,
  createSecretFile,
  importSecretFile,
  updateSecretFile,
  editSecretFile,
  readSecretFile,
  writeSecretFile,
  registerUser,
  addUser,
  removeUser,
  createGroup,
  deleteGroup,
  addGroupMember,
  removeGroupMember,
  setFileAccess,
  encryptedFileFor,
  plaintextFileFor,
  materializeSecretFiles,
  cleanSecretFiles,
  statusSecretFiles,
  diffSecretFiles,
  runWithFiles,
  type CreatedSecretFile,
  type ImportedSecretFile,
  type EditConflictResolution,
  type OpenedSecretFile,
  type SavedSecretFile,
  type SecretFileStatus,
  type SecretFileDiff,
  type CleanResult,
  type RunResult,
  type FileAccess,
  type NewUser,
} from "./operations.js";
