export { GitVaultyError, TrackedPlaintextError } from "./errors.js";
export { normalizeUsername, parseRecipient } from "./recipient.js";
export { findRepository, type Repository } from "./repository.js";
export {
  cleanupAbandonedEditDirectories,
  DEFAULT_EDIT_TEMP_GRACE_PERIOD_MS,
  type EditTempCleanupOptions,
  type EditTempCleanupResult,
} from "./edit-temp.js";
export { createIdentity, currentRecipient, identityFile, readIdentity, readStoredIdentity, restoreIdentity, type StoredIdentity } from "./key.js";
export {
  normalizeGitVaultyUser,
  normalizeGitVaultyGroup,
  normalizeGroupName,
  normalizeFileGrant,
  normalizeSecretFile,
  fileGrantFor,
  filesForUser,
  readRegistry,
  writeRegistry,
  recipientsFor,
  usernamesFor,
  type Registry,
  type GitVaultyUser,
  type GitVaultyGroup,
  type SecretFileGrant,
} from "./registry.js";
export {
  initialize,
  createSecretFile,
  importSecretFile,
  updateSecretFile,
  editSecretFile,
  addUser,
  removeUser,
  createGroup,
  deleteGroup,
  addGroupMember,
  removeGroupMember,
  setFileAccess,
  encryptedFileFor,
  plaintextFileFor,
  materializeSecretFiles,
  cleanSecretFiles,
  statusSecretFiles,
  runWithFiles,
  type CreatedSecretFile,
  type ImportedSecretFile,
  type EditConflictResolution,
  type SecretFileStatus,
  type CleanResult,
  type RunResult,
  type FileAccess,
  type NewUser,
} from "./operations.js";
